export const LOAD_USER  = 'LOAD_USER'
export const DRAW_LOAD_USER = 'DRAW_LOAD_USER'
export const SUCCESS_LOAD_USER = 'SUCCESS_LOAD_USER'
export const FAILED_LOAD_USER = 'FAILED_LOAD_USER'

export const ADD_USER  = 'ADD_USER'
export const DRAW_ADD_USER = 'DRAW_ADD_USER'
export const SUCCESS_ADD_USER = 'SUCCESS_ADD_USER'
export const FAILED_ADD_USER = 'FAILED_ADD_USER'

export const DELETE_USER  = 'DELETE_USER'
export const DRAW_DELETE_USER = 'DRAW_DELETE_USER'
export const SUCCESS_DELETE_USER = 'SUCCESS_DELETE_USER'
export const FAILED_DELETE_USER = 'FAILED_DELETE_USER'

export const RESEND_USER  = 'RESEND_USER'
export const DRAW_RESEND_USER = 'DRAW_RESEND_USER'
export const SUCCESS_RESEND_USER = 'SUCCESS_RESEND_USER'
export const FAILED_RESEND_USER = 'FAILED_RESEND_USER'

export const EDIT_USER  = 'EDIT_USER'
export const DRAW_EDIT_USER = 'DRAW_EDIT_USER'
export const SUCCESS_EDIT_USER = 'SUCCESS_EDIT_USER'
export const FAILED_EDIT_USER = 'FAILED_EDIT_USER'

export const FILTER_USER = 'FILTER_USER'
export const UPDATE_FILTER = 'UPDATE_FILTER'
